{
	"version": 1504530443,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/nome1-sheet0.png",
		"images/respostas-sheet0.png",
		"images/blocopergunta-sheet0.png",
		"images/fundovenceu-sheet0.png",
		"images/logomarca-sheet0.png",
		"images/logomarca-sheet1.png",
		"images/logomarca-sheet2.png",
		"images/logomarca-sheet3.png",
		"images/logomarca-sheet4.png",
		"images/teladegameover-sheet0.png",
		"images/fundo.png",
		"images/fundo2.png",
		"images/fundo3.png",
		"images/fundo4.png",
		"images/fundo5.png",
		"images/fundo6.png",
		"images/pelicula-sheet0.png",
		"images/moldura-sheet0.png",
		"images/anapaula-sheet0.png",
		"images/peliculaazul-sheet0.png",
		"images/efeitocorte-sheet0.png",
		"images/criador-sheet0.png",
		"images/redessociais-sheet0.png",
		"images/bomba-sheet0.png",
		"images/barreira-sheet0.png",
		"images/fundotv-sheet0.png",
		"images/scorre-sheet0.png",
		"images/ihudopcao-sheet0.png",
		"images/ihudpause-sheet0.png",
		"images/bmusica-sheet0.png",
		"images/bmusica-sheet1.png",
		"images/breiniciar-sheet0.png",
		"images/bfechar-sheet0.png",
		"images/fundop-sheet0.png",
		"images/bopcao-sheet0.png",
		"images/fundomenu-sheet0.png",
		"images/botãoplay-sheet0.png",
		"images/botãoinstrução-sheet0.png",
		"images/botãocredito-sheet0.png",
		"images/instruções-sheet0.png",
		"images/creditos-sheet0.png",
		"images/creditos2-sheet0.png",
		"images/botãoback-sheet0.png",
		"media/bruno martini - sun goes down ft. isadora-[audiotrimmer.com].ogg",
		"media/a fazenda 5 - nicole surta e diz que peões fizeram cocô na parede - 19 06 2012-[audiotrimmer.com].ogg",
		"media/a gente que tem silicone a gente sente-[audiotrimmer.com].ogg",
		"media/e o meu cabelo solto de prancha.ogg",
		"media/eu sou rolezeira-[audiotrimmer.com].ogg",
		"media/eu vou expor ela na internet eu vou expor ela!-[audiotrimmer.com].ogg",
		"media/ja acabou jessica oficial-[audiotrimmer.com].ogg",
		"media/luisa casa roqueta 029.mp4-[audiotrimmer.com].ogg",
		"media/olha ela bbb 16-[audiotrimmer.com].ogg",
		"media/pérola glória pires no oscar não sou capaz de opinar adorei-[audiotrimmer.com].ogg",
		"media/quem gostou bate palma quem nÃo gostou paciÊncia-[audiotrimmer.com].ogg",
		"media/sangue de jesus tem poder e faz o inferno estremecer - dona cutilada-[audiotrimmer.com].ogg",
		"media/se me atacá eu vou atacá - inês brasil-[audiotrimmer.com].ogg",
		"media/senhora volta aqui  - repórter corre ao vivo atras de senhora (1)-[audiotrimmer.com].ogg",
		"media/xuxa - aham cláudia senta lá (vídeo original)-[audiotrimmer.com].ogg",
		"media/taylor swift - look what you made me do (lyric video).ogg",
		"media/efeitos sonoros memes zueira-[audiotrimmer.com].ogg",
		"media/amiseravi.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}