{
	"version": 1500178558,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/personagem-sheet0.png",
		"images/bloco-sheet0.png",
		"images/caminho-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/inimigo-sheet1.png",
		"images/inimigo-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/bala-sheet0.png",
		"images/particles.png",
		"images/casacarol-sheet0.png",
		"images/particlesinimigo.png",
		"images/vida-sheet0.png",
		"images/vida-sheet1.png",
		"images/vida-sheet2.png",
		"images/comida-sheet0.png",
		"images/moedas-sheet0.png",
		"images/moedas-sheet1.png",
		"images/comida1-sheet0.png",
		"images/comida2-sheet0.png",
		"images/portal-sheet0.png",
		"images/portal-sheet1.png",
		"images/basedoportal-sheet0.png",
		"images/lavadefogo-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/barradevida-sheet0.png",
		"images/barradevidavazio-sheet0.png",
		"images/sprite-sheet0.png",
		"images/fundomenu-sheet0.png",
		"images/botãoinfo-sheet0.png",
		"images/botãocredito-sheet0.png",
		"images/botãoplay-sheet0.png",
		"images/paoladesenho-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/parabens-sheet0.png",
		"images/vctombou-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/fundo-sheet0.png",
		"images/botãovoltar-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sound-sheet0.png",
		"images/teladeinfo1-sheet0.png",
		"images/creditos-sheet0.png",
		"media/laser1.m4a",
		"media/laser1.ogg",
		"media/som-de-moeda-do-sonic-mp3.m4a",
		"media/som-de-moeda-do-sonic-mp3.ogg",
		"media/86026__harpoyume__explosion-3.m4a",
		"media/86026__harpoyume__explosion-3.ogg",
		"media/320673__inbeeld__eating-a-baguette.m4a",
		"media/320673__inbeeld__eating-a-baguette.ogg",
		"media/352208__inspectorj__smashing-wooden-fence-c.m4a",
		"media/352208__inspectorj__smashing-wooden-fence-c.ogg",
		"media/214213_taira-komori_damage2 (online-audio-converter.com).ogg",
		"media/264447__kickhat__open-button-2.m4a",
		"media/264447__kickhat__open-button-2.ogg",
		"media/368367__thezero__game-over-sound.m4a",
		"media/368367__thezero__game-over-sound.ogg",
		"media/karol conka tombei feat. tropkillaz (kondzilla)- (online-audio-converter.com).ogg",
		"media/priscilla alcantara tanto faz (Áudio)- (online-audio-converter.com).ogg",
		"media/the last of us trilha sonora 1 (online-audio-converter.com).ogg",
		"media/345666__mattix145__game-over-voice-effect-01.m4a",
		"media/345666__mattix145__game-over-voice-effect-01.ogg",
		"media/assassin39s creed 2 (2009) venice escape (soundtrack ost) (online-audio-converter.com).ogg",
		"media/game over joelma calypso nova músicanovo cd- (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}